### PR TITLE
Upgrade drivers, plugins, jdk, and add kv2 engine, github token and authentication classes

### PR DESCRIPTION
**Pull request by HomeOfTheWizard**
upgraded plugins:

  - maven surefire
  - maven failsafe
  - maven compile
  - maven plugin and related
  - junit
  - docker plugin
  - guava
 
Upgraded compile settings to java 11

Upgraded vault driver to use KV2 engine

Added github token authentication method.   
In order to run the integration tests, you need to pass a [github token](https://github.com/homeofthewizard/vault-maven-plugin/blob/a5001c62ba9bf9081cb2dad4c8cf96908b927d88/pom.xml#L69) as environment variable in your pom.xml,      
and change accoringly the setup script [enable-github-auth.sh](https://github.com/homeofthewizard/vault-maven-plugin/blob/master/docker/vault/enable-github-auth.sh)

### CODE REVIEW

**Comment by homeofthewizard** [comment]
Hi, Is it possible to add the JDK 11 to the CI environment ? or should I rollback to java 8 ?

**Review by superjerico — APPROVED** [review]
approving changes to keep project up to date with latest Vault API

**Comment by garvit-joshi** [comment]
Hi @HomeOfTheWizard ,

I dont think that the project is quite maintained at this point in time. It would be easier if you could deploy your fork to maven as a new dependency.
Thanks in advance.

**Comment by garvit-joshi** [comment]
I see you already did that.

Thanks.

**Pull request closed without merging**
